### ISSUE TITLE
Stylelint is scanning imported node modules which causes failure with vite-plugin-pages

### ISSUE THREAD

**Issue by ElMassimo** [AMatlash/vite-plugin-stylelint#1]
### Description 📖 

The plugin is scanning my project's postcss files correctly, but it's also attempting to scan `vite-plugin-pages/client`, which causes an error with `vite-plugin-pages`, causing the page not to load.

### Reproduction 🐞 

I used [Vitesse](https://github.com/antfu/vitesse) as the base setup, and I think you should be able to replicate the problem by creating a new app with `npx degit antfu/vitesse my-vitesse-app`, and adding this plugin.

### Workarounds 🔨 

The error stops happening if I explicitly exclude any vite dependency, which makes me think the `node_modules` default is not really excluding certain modules.

```js
  plugins: [
    VitePluginStylelint({ exclude: /(node_modules|vite)/ }),
```

It also works if I explicitly specify extensions:

```js
  plugins: [
    VitePluginStylelint({ include: './src/**/*.(vue|scss|css|postcss)' })
```

### Screenshots 📷 

<img width="940" alt="Screen Shot 2021-02-11 at 19 55 38" src="https://user-images.githubusercontent.com/1158253/107709092-63840e80-6ca3-11eb-830c-9c6ed7b35b72.png">

**Comment by AMatlash** [comment]
Stylelint by default can handle various file extensions.
![image](https://user-images.githubusercontent.com/36326596/107717557-f1ccb480-6ce4-11eb-8be7-80dd7665b686.png)

So I think it`s up to plugin user to define what should and what should not be processed by linter. And I am not sure we could predict every vite-specific id that triggers plugin's hook.

However, I've added recommended extensions in default `options.include`. This workaround should be enough for plugin to properly work in that case.

**Comment by ElMassimo** [comment]
Thanks! I think with those defaults it should work for most purposes.
